### ISSUE TITLE
code optimization suggestion

### ISSUE THREAD

**Issue by tech-a-go-go** [doowb/sma#1]
Hi there

https://github.com/doowb/sma/blob/master/index.js#L35
```
33:  var idx = num - 1;
34:  while (++idx < len) {
35:    res.push(fn(avg(arr, idx, idx < num ? idx : num)));
36:  }
```

Why do you check if idx is smaller than num (idx < num ? idx : num) on line 35 ??
idx can never be smaller than num because idx is num -1 and pre-incremented on line 34.
I guess that doesn't cause a problem but unnecessary.

Cheers

**Comment by doowb** [comment]
@tech-a-go-go you're right. I don't see how `idx` can ever be less than `num`. PRs are welcome, otherwise I'll try to get it updated soon.
