### ISSUE TITLE
Usage with decimals

### ISSUE THREAD

**Issue by mattgabor** [doowb/sma#3]
I tried using this library with a decimal based array, and it returns ["0.00",  "0.00", ....]

Is it intended to be used with decimals or can it be extended to?

**Comment by doowb** [comment]
Do you have an example of the input and the actual expected results? I thought there were tests using decimals, but there aren't.

**Comment by doowb** [comment]
Thanks for the issue. I fixed it so if you get the latest from npm you should be able to use decimals now.

**Comment by mattgabor** [comment]
confirmed that the new version works with decimals! Thanks, this function is exactly what I needed 🙏
