### ISSUE TITLE
Ability to pad the returned array with 'undefined' / lesser window sizes for values that can't be calculated

### ISSUE THREAD

**Issue by popey456963** [doowb/sma#4]
Is useful for my use case to ensure that the output array is the same size as the input array, even if the data is more odd.

**Comment by doowb** [comment]
I'm open to suggestions and a PR with an option to do something like this (defaulting to current functionality).

However, it might make sense to wrap `sma` with something that does that.

For example, adding `undefined` to the beginning of the array:

```js
const arr = [/* your input array */];
const range = 10;
const result =  [
  ...new Array(range),
  ...sma(arr, range)
];
```

Adding `0` to the beginning of the array:

```js
const arr = [/* your input array */];
const range = 10;
const result =  [
  ...(new Array(range)).fill(0),
  ...sma(arr, range)
];
```

**Comment by popey456963** [comment]
Yeah, in the end I ended up padding 50% of the window size to the beginning and 50% to the end.  It worked well for the purpose of graphing the lines.

I was just curious whether this should be built into the library, but I also like the libraries simplicity.  I'm going to close this ticket I think.
